linux: &linux
  os: linux
  dist: bionic
  language: python
  env: CC=gcc-7 CXX=g++-7

osx: &osx
  os: osx
  language: generic

matrix:
  include:
    - <<: *linux
      python: "3.6"
    - <<: *linux
      python: "3.7"
    - <<: *linux
      python: "3.8"
    - <<: *osx
      osx_image: xcode11.3
      env: 
        - pyv="3.6.10"
    - <<: *osx
      osx_image: xcode11.3
      env: 
        - pyv="3.7.6"
    - <<: *osx
      osx_image: xcode11.3
      env: 
        - pyv="3.8.2"

before_install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh
  - ls -la
  - git checkout $TRAVIS_BRANCH
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then eval "$(pyenv init -)"; pyenv activate pyCHM; fi
  - pip install --upgrade pip
  - ls -la
  - pip install .
deploy:
  provider: script
  script: pwd && ls -la && bash ./.travis/deploy.sh