[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CHM"
version = "1.5.0"
authors = [
    {name="Chris Marsh"}
]
description = "python tools for CHM"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ['numpy', 'xarray', 'netCDF4', 'pandas',
                'gdal', 'dask[complete]', 'uxarray',
                 'rioxarray', 'rasterio', 'ninja', 'cftime', 'pyproj']


[project.urls]
Homepage = "https://github.com/Chrismarsh/pyCHM"

[project.scripts]
chm_pvd_from_dir = "CHM.tools.pvd_from_dir:main"
chm_validateJSON = "CHM.tools.validate_json:main"
chm_windmapper2mesher = "CHM.tools.windmapper2mesher:main"
chm_ugrid2grid = "CHM.tools.ugrid2grid:main"

